# Generated by Django 4.2.30 on 2026-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioCV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidodata',
            name='Autor',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='Fuentes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='Obras',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='contraseña',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='instituciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='nombre_repo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='plataforma',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='token_GitHub',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='token_GitLab',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='topics',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contenidodata',
            name='url_repo',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contenidodata',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
