# Generated by Django 4.2.30 on 2026-04-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioCV', '0002_contenidodata_autor_contenidodata_fuentes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openalex_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
