# Generated by Django 4.2.30 on 2026-04-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioCV', '0003_userprofile_openalex_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
