# Generated by Django 4.2.30 on 2026-04-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioCV', '0004_userprofile_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lm_studio_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
