# Generated by Django 4.2.30 on 2026-05-02 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioCV', '0005_userprofile_lm_studio_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gemini_api_key',
            new_name='nvidia_api_key',
        ),
    ]
