# Generated by Django 6.1.1 on 2026-10-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioCV', '0008_encrypt_user_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ia_base_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ia_model',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
