# Generated by Django 6.1.1 on 2026-10-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioCV', '0009_userprofile_ia_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidodata',
            name='recurso',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='contenidodata',
            constraint=models.UniqueConstraint(fields=('recurso', 'usuario'), name='recurso_unico_por_usuario'),
        ),
    ]
