# Generated by Django 6.1.1 on 2026-10-07 23:20

import portfolioCV.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioCV', '0010_recurso_unico_por_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='huggingface_token',
            field=portfolioCV.fields.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='huggingface_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
