"""
Django settings for PortfolioGenerator project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# En True muestra la pantalla amarilla de error de Django con detalles del código.
# En producción DEBE estar en False para que los usuarios vean la página 404/500 estándar.
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
# Se lee de la variable de entorno DJANGO_SECRET_KEY. Solo en local (DEBUG=True) hay valor por defecto;
# en producción, si falta, la app se para en vez de arrancar con una clave pública.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-solo-para-local"
    else:
        raise ImproperlyConfigured("Falta la variable DJANGO_SECRET_KEY")

# Clave (Fernet) con la que se cifran los tokens/API keys de los usuarios en la BD.
# Generar con: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Si no se define, se deriva de SECRET_KEY (válido en local; en producción definirla explícitamente).
FIELD_ENCRYPTION_KEY = os.environ.get("FIELD_ENCRYPTION_KEY", "")


# Dominios desde los que se permite acceder a la aplicación.
# Lista separada por comas en DJANGO_ALLOWED_HOSTS (en producción: creator.danimh.dev).
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# Application definition

# INSTALLED_APPS define los módulos activados en tu proyecto Django.
# Si no está aquí, Django ignora las tablas y URLs de esa app.
INSTALLED_APPS = [
    # --- Apps nativas de Django ---
    'django.contrib.admin',      # Panel de administración (/admin)
    'django.contrib.auth',       # Sistema base de usuarios y permisos
    'django.contrib.contenttypes',
    'django.contrib.sessions',   # Gestiona la tabla django_session en BD
    'django.contrib.messages',   # Los mensajitos flash verdes/rojos que salen arriba
    'django.contrib.staticfiles',# Sirve CSS, JS e imágenes
    'django.contrib.sites',      # Requerido por allauth (SITE_ID = 1)
    
    # --- Apps de terceros (Allauth para Login Social) ---
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.github', # Proveedor OAuth GitHub
    'allauth.socialaccount.providers.google', # Proveedor OAuth Google
    
    # --- Nuestra App Principal ---
    'portfolioCV',
]

# Identificador del sitio para allauth (corresponde a un registro en la tabla django_site)
SITE_ID = 1

# Backends de autenticación: indican a Django CÓMO comprobar si un usuario es válido.
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',           # Login normal (usuario/contraseña en BD)
    'allauth.account.auth_backends.AuthenticationBackend', # Login Social (GitHub/Google)
]

# MIDDLEWARE: Capas que interceptan las peticiones HTTP (request) ANTES de llegar a views.py
# y las respuestas (response) ANTES de enviarlas al navegador.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # Lee/crea la cookie 'sessionid'
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',             # Bloquea POSTs si no traen {% csrf_token %}
    'django.contrib.auth.middleware.AuthenticationMiddleware',# Mete al usuario en request.user
    'django.contrib.messages.middleware.MessageMiddleware',  # Carga los mensajes flash
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',          # Lógica intermedia del login social
]

ROOT_URLCONF = 'PortfolioGenerator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'portfolioCV.context_processors.flags',  # SOCIAL_LOGIN y ALLOW_LOCAL_LLM en las plantillas
            ],
        },
    },
]

WSGI_APPLICATION = 'PortfolioGenerator.wsgi.application'


# Database
# Aquí se define dónde y cómo guardar los datos (Modelos).
# Estamos usando SQLite, que guarda toda la BD en un solo fichero local llamado db.sqlite3.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# URL base pública desde el navegador (ej: tusitio.com/static/css/style.css)
STATIC_URL = 'static/'

# Carpeta FISICA en el servidor donde se juntan todos los estáticos al hacer 'collectstatic'
# Aquí se juntan los estáticos con `collectstatic`; en producción los sirve WhiteNoise.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# Hace que los IDs de la base de datos (id) se autoincrementen y sean enteros grandes.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- RUTAS DE AUTENTICACIÓN (Login settings) ---
LOGIN_URL = '/login/'              # Si el @login_required salta, redirige aquí
LOGIN_REDIRECT_URL = '/'           # Si haces login con éxito, vas al index
LOGOUT_REDIRECT_URL = '/'          # Si haces logout, vas al index

# --- CONFIGURACIÓN DEL LOGIN SOCIAL (Allauth settings) ---
ACCOUNT_EMAIL_VERIFICATION = 'none' # No pedimos confirmar el email por correo electrónico
ACCOUNT_LOGIN_ON_SIGNUP = True      # Tras registrarte por primera vez con GitHub, te hace login directo
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
SOCIALACCOUNT_LOGIN_ON_GET = True   # Al pinchar en GitHub se salta una pantalla intermedia de confirmación
SOCIALACCOUNT_AUTO_SIGNUP = True    # Crea el usuario en nuestra BD automáticamente si GitHub dice que es OK

# --- FLAGS DE ENTORNO ---
# El modo "LM Studio local" solo tiene sentido en tu ordenador. En producción: False.
ALLOW_LOCAL_LLM = os.environ.get("ALLOW_LOCAL_LLM", "False") == "True"
# Botones de login con GitHub/Google (solo donde estén configuradas las apps OAuth).
SOCIAL_LOGIN = os.environ.get("SOCIAL_LOGIN", "False") == "True"
# Proveedor y modelo de IA por defecto, para los usuarios que no ponen los suyos en Tokens.
# NVIDIA retira modelos (gemma-2-2b-it dejó de existir el 2026-07-27): si pasa de nuevo,
# basta con cambiar NVIDIA_MODEL en el entorno.
NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"
NVIDIA_MODEL = os.environ.get("NVIDIA_MODEL", "nvidia/nemotron-3.5-lightning-30b-a3b")

# --- LOGGING ---
# Con DEBUG=False Django no muestra los errores 500 en ningún sitio; así salen por consola (docker compose logs).
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {"django.request": {"handlers": ["console"], "level": "ERROR"}},
}
